# Generated by Django 5.0.4 on 2024-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
