version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "student_management"
      MYSQL_ROOT_PASSWORD: "studentmanagement"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "studentmanagement"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:studentmanagement@db:3306/student_management"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
